### ISSUE TITLE
Routes do not respect the ical_export_start and ical_export_end fields (bug or feature?)

### ISSUE THREAD

**Issue by complanar** [janborg/contao-ical-bundle#10]
The ics files generated unter /ical/calender/[alias] do not respect the settings made in the backend fields `ical_export_start` and `ical_export_end`.

If you activate the generation of an additional ical file in `/share/…` these generated files do respect those settings though.

Is this intended or not? Or am I missing an option that can be made in `config.yml`?

**Comment by janborg** [comment]
This was definitely a bug. 

Should be fixed in [0.2.3](https://github.com/janborg/contao-ical-bundle/releases/tag/0.2.3)

Thanks @complanar  for finding it!
