### ISSUE TITLE
Typo in README.md

### ISSUE THREAD

**Issue by complanar** [janborg/contao-ical-bundle#11]
The option in config.yml has a typo: It reads `janborg_contaoical` but in `/src/CalendarIcalExporter.php` it is spelled `janborg_contao_ical` (line 57).

Please be aware that correcting this typo can introduce breaking changes no matter which way you correct it. It may be that people found out about this and "corrected" the spelling in `config.yml` (as I did) and – maybe much more seldom – they did it the other way round (which is kind of naive because it would break update compatibility). But of course as one can not know which way you meant it, both options are possible.

**Comment by janborg** [comment]
Thank you, but fixing a typo in a README can't be a breaking change, IMHO. 

Will fix it asap.

**Comment by complanar** [comment]
> Thank you, but fixing a typo in a README can't be a breaking change, IMHO.

That’s right in general. But it could break a custom `config.yml` if someone had the idea to change the code in `/src/CalendarIcalExporter.php` instead of `config.yml`. 
Clearing and regenerating the contao cache will fail in this case because of an "unknown" configuration option. This way I found out about the typo ;-).

Thank you for fixing it.
